### ISSUE TITLE
네이버 검색 책 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#100]
플랫폼: windows
해상도: FHD
브라우저: Firefox

예시링크 : https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=영화

![image](https://user-images.githubusercontent.com/42881884/131780668-572400da-a0d8-49d9-b9ad-f48ff9e50400.png)

**Comment by OrigamiDream** [comment]
Fix: c06969b1142026f336a5d76b5b85e2e2b69f227b
