### ISSUE TITLE
네이버 뉴스: 스크랩

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#101]
https://news.naver.com/main/scrap/folderList.naver?scrapItem.officeId=081&scrapItem.articleId=0003213312
![image](https://user-images.githubusercontent.com/37479424/132110126-923e8c97-44b3-4b85-b3ed-e2f0f0d44edf.png)
뉴스 페이지에서 스크랩 버튼 누르면 나오는 현상

**Comment by OrigamiDream** [comment]
Fix: f887667d95d7d418209f95329d1a1d5aedfd8a5e
