### ISSUE TITLE
네이버 카페 상품등록 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#102]
플랫폼: windows
해상도: FHD
브라우저: Firefox

예시링크: https://cafe.naver.com/ca-fe/cafes/29926076/menus/5/articles/write?boardType=L

![image](https://user-images.githubusercontent.com/42881884/132123382-84b91f08-4f5e-4d34-afcc-a1bafb940e9c.png)

**Comment by winter0729** [comment]
하단 글 쓰는부분 T 버튼 화이트 작업필요.

![image](https://user-images.githubusercontent.com/42881884/132123399-26d6d956-6dd4-45ea-9831-c15ca10a7fc2.png)

**Comment by OrigamiDream** [comment]
Fix: 34f79ebaec631aae3a774cb328efe11d6e1a7273, 34f79ebaec631aae3a774cb328efe11d6e1a7273
