### ISSUE TITLE
네이버 뉴스: 목록

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#103]
![image](https://user-images.githubusercontent.com/37479424/132128400-ed17a1dc-ce83-4df1-bca8-53ef0bae3d29.png)
![image](https://user-images.githubusercontent.com/37479424/132128404-0109c391-5da3-4403-aff2-4d53e0a96823.png)
다크 테마에서는 목록 위에 약간의 빈 공간이 있음

**Comment by OrigamiDream** [comment]
Fix: 4e389b266386e022be793c698eb9c57514f31b1e
