### ISSUE TITLE
네이버 검색: 대선

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#106]
https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=%EB%8C%80%EC%84%A0&oquery=%EB%82%B4%ED%88%AC%ED%91%9C%EC%86%8C%EC%B0%BE%EA%B8%B0&tqi=hg3MRdp0JXossifXiywssssstiN-397216
![image](https://user-images.githubusercontent.com/37479424/132983217-2827f1ba-7306-4c89-ab1a-4e08c6a5fe38.png)

**Comment by OrigamiDream** [comment]
Fix: 19e3557cf60e8f0ae2ba801ea24726d29c0677b4
