### ISSUE TITLE
네이버 검색 역대 대통령 인물 기록 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#110]
플랫폼: windows
해상도: FHD
브라우저: Firefox

예시링크:  https://search.naver.com/search.naver?sm=tab_sug.top&where=nexearch&query=박근혜

![image](https://user-images.githubusercontent.com/42881884/134814796-e326009f-1f6e-401d-af56-e99c30edaa9e.png)

**Comment by OrigamiDream** [comment]
Fix: ae41ff6e56391059e79ecb8fb12774202b1a3728
