### ISSUE TITLE
네이버 검색 같은 이름 다른 인물 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#111]
플랫폼: windows
해상도: FHD
브라우저: Firefox

예시링크:  https://search.naver.com/search.naver?sm=tab_sug.top&where=nexearch&query=박근혜

![image](https://user-images.githubusercontent.com/42881884/134814821-703636cb-3d3b-4dbc-8437-4b746afd5b8b.png)

**Comment by OrigamiDream** [comment]
Fix: ae41ff6e56391059e79ecb8fb12774202b1a3728
