### ISSUE TITLE
네이버 동영상 추천 리스트

### ISSUE THREAD

**Issue by Radingth** [DarkenPages/Naver-Dark#114]
https://search.naver.com/search.naver?where=video&sm=tab_jum&query=%EB%84%A4%EC%9D%B4%EB%B2%84+%EC%98%81%EC%83%81

동영상 탭
![124124145](https://user-images.githubusercontent.com/16663489/136155704-1cd9cf19-e134-4e36-a25a-55f176864a32.PNG)

**Comment by OrigamiDream** [comment]
Fix: e0b1fd560076c20c0ec2ec473a057b03e025367f
