### ISSUE TITLE
네이버 메일: 파일 전송 팝업

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#119]
![image](https://user-images.githubusercontent.com/37479424/140648044-f9585307-5c5a-4a9b-b74e-0797d6e187b3.png)
mail.naver.com 직접 사용자가 전송해야 확인 가능

**Comment by OrigamiDream** [comment]
Fix: 68043b32ec9ed0bf2cbd3a0f97b9469cf27bf5bb
