### ISSUE TITLE
검색: 인물?

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#120]
https://search.naver.com/search.naver?ie=UTF-8&query=sojourn&sm=chr_hty
![image](https://user-images.githubusercontent.com/37479424/141941964-c69a2620-b00c-4bbc-a604-c7ef81d66e6f.png)

**Comment by OrigamiDream** [comment]
Fix: 46f85335fea0bb630b0a90afff6fe5cdcedea6af
