### ISSUE TITLE
게이버 검색: 고수

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#123]
![image](https://user-images.githubusercontent.com/37479424/141966235-016281da-ac0a-4f2c-98b8-a17ea47582e5.png)
https://search.naver.com/search.naver?query=%EA%B3%A0%EC%88%98
고수의 실력이 필요합니다.

**Comment by OrigamiDream** [comment]
Fix: 5d6ed4f11b95c6e80f246f8939598986d6f1a7a4
