### ISSUE TITLE
게이버 검색: 일출일몰시간

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#127]
![image](https://user-images.githubusercontent.com/37479424/141967516-758b1922-4503-4870-9e5e-57fe4a3b1392.png)
https://search.naver.com/search.naver?sm=tab_etc&query=%C0%CF%C3%E2%C0%CF%B8%F4%BD%C3%B0%A3

**Comment by OrigamiDream** [comment]
Fix: 83ec19848b08e34bda610e2c24a22b1d662fb9a5
