### ISSUE TITLE
네이버 메인: 뉴스스탠드

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#128]
![image](https://user-images.githubusercontent.com/37479424/141967904-3f6236bd-7ec2-4614-99d1-6cb4f5339eee.png)
왼쪽 텍스트와 로고
https://www.naver.com/

**Comment by OrigamiDream** [comment]
Fix: 1a95ad6b8055ed3568b7547e4d93a17e5df353b1
