### ISSUE TITLE
네이버 검색: 네코미미?

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#129]
https://search.naver.com/search.naver?ie=UTF-8&query=%EB%84%A4%EC%BD%94%EB%AF%B8%EB%AF%B8&sm=chr_hty
![image](https://user-images.githubusercontent.com/37479424/141969444-d61b700f-0077-47c0-8db5-562cb9c06686.png)

**Comment by OrigamiDream** [comment]
Fix: 3fc72a87a689ec4951ba8725f86ec31565af3bfd
