### ISSUE TITLE
네이버 검색: 코스프레 (인플루언서)

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#130]
![image](https://user-images.githubusercontent.com/37479424/141969610-0900acc3-63df-4a0a-8979-45c13688a5dd.png)
https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=%EC%BD%94%EC%8A%A4%ED%94%84%EB%A0%88

**Comment by OrigamiDream** [comment]
Fix: 04ee0a733eb851cdcba736647f90ae3fa134799e
