### ISSUE TITLE
네이버 검색: 어학사전

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#131]
![image](https://user-images.githubusercontent.com/37479424/141969757-70a67e6c-1c21-444f-90b2-4a66539354dc.png)
https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=%EC%96%B4%ED%95%99%EC%82%AC%EC%A0%84

**Comment by OrigamiDream** [comment]
Fix: 7ff75a9ec50fe6f0326c09605e7192eea3320173
