### ISSUE TITLE
네이버 뉴스: 게시글 index 목록? (UX 관련)

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#132]
어떤게 active인지 알 수 없음. 화이트 기준에서는 border도 있고 그랬는데 다크에서는 존재하지 않음. 따라서 보완 요청을 합니다.
![image](https://user-images.githubusercontent.com/37479424/142012515-7cb91a89-234b-4ae5-a884-ba72991146e8.png)
![image](https://user-images.githubusercontent.com/37479424/142012537-7ee85153-3e52-426a-bd13-348a9c05f9b0.png)
https://news.naver.com/main/main.naver?mode=LSD&mid=shm&sid1=105#&date=%2000:00:00&page=6

**Comment by OrigamiDream** [comment]
Safari 15.1 기준 확인이 불가능합니다.
브라우저 정보의 상세한 기재와 개발자 도구에 나타나는 스타일 적용 상태 등을 첨부해주세요.

**Comment by ilsubyeega** [comment]
Fixed via https://github.com/DarkenPages/Naver-Dark/commit/4c0d3af734bc1efafbe410af0c27e1195cb77628
