### ISSUE TITLE
네이버 검색: 테슬라

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#135]
https://search.naver.com/search.naver?ie=UTF-8&query=%ED%85%8C%EC%8A%AC%EB%9D%BC&sm=chr_hty
![image](https://user-images.githubusercontent.com/37479424/142767518-6a9a9751-8b8c-499c-9bcd-a13d0256b3bd.png)

**Comment by OrigamiDream** [comment]
Fix: e900bbcafb3b4ac16c9f0555da6adabcaccef84a
