### ISSUE TITLE
네이버 검색 : 레시피

### ISSUE THREAD

**Issue by Radingth** [DarkenPages/Naver-Dark#136]
윈도우 11
크롬

![image](https://user-images.githubusercontent.com/16663489/143431463-3a7ed897-861a-4a19-908b-9157abc517d1.png)

https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=%EB%A0%88%EC%8B%9C%ED%94%BC&oquery=%EB%82%A0%EC%94%A8&tqi=hi9YDwprvTVssF2DeKVssssssol-319511

**Comment by OrigamiDream** [comment]
Fix: a59d7d2f2161a8ea1a6afa2614be48231ccd4665
