### ISSUE TITLE
네이버 검색 : 기업분석

### ISSUE THREAD

**Issue by Radingth** [DarkenPages/Naver-Dark#137]
크롬 
윈도우 11

![image](https://user-images.githubusercontent.com/16663489/143431603-7a8e2f5e-7098-4eb8-98e6-17a84c2d6e2e.png)

https://search.naver.com/search.naver?where=nexearch&query=%EA%B8%B0%EC%97%85%EB%B6%84%EC%84%9D&sm=tab_stc

**Comment by OrigamiDream** [comment]
Fix: fad1a46ddc42cc9af7df8615896ac7737b4216c6
