### ISSUE TITLE
네이버 검색 : 음식

### ISSUE THREAD

**Issue by Radingth** [DarkenPages/Naver-Dark#139]
윈도우 11
크롬

![image](https://user-images.githubusercontent.com/16663489/143432106-e0d6b492-590b-4d90-9eec-ff22be3d9630.png)

https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=%EC%9D%8C%EC%8B%9D&oquery=%EB%A1%9C%EB%98%90&tqi=hi9wysprvN8ssRYVXPdsssssthZ-073943

**Comment by OrigamiDream** [comment]
Fix: 649be6041c0d4a343fb7836743be614bd8a14811
