### ISSUE TITLE
[Feature Request] Support Naver Dictionary

### ISSUE THREAD

**Issue by coughingmouse** [DarkenPages/Naver-Dark#14]
Naver Dictionary is a renowned dictionary not only within the Korean-learning community but for other languages as well. 

Although adding https://dict.naver.com on the CSS file helps quite a bit, there are a few critical readability problems, such as the links and the Chinese letters within [ ] brackets.

All in all, it would be great if Naver Dictionary were supported in this script.

Best wishes and thanks!

**Comment by OrigamiDream** [comment]
NAVER has added built-in dark mode in Dictionary.
The new appearance will be enabled when you enable systemwide dark appearance.

This issue has been resolved by NAVER in almost 3 years. 😢
