### ISSUE TITLE
네이버 검색 : 심심해

### ISSUE THREAD

**Issue by Radingth** [DarkenPages/Naver-Dark#140]
윈도우 11
크롬

![image](https://user-images.githubusercontent.com/16663489/143432332-d0830472-fdb8-4948-90bf-3ab296f459a5.png)

https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=%EC%8B%AC%EC%8B%AC%ED%95%B4&oquery=%EB%84%A4%EC%9D%B4%EB%B2%84+%EC%9D%B4%EC%8A%A4%ED%84%B0%EC%97%90%EA%B7%B8&tqi=hi9x4sprvxsssAsoKEwssssssHo-021221

**Comment by OrigamiDream** [comment]
Fix: 282c97d62bdd8d439db8b94b5ac10f3662d99655
