### ISSUE TITLE
네이버 카페: 등급 목록

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#142]
![image](https://user-images.githubusercontent.com/37479424/143733782-8e2c3ab7-21a9-4c98-8790-f6ef671af4b9.png)
우마공 기준
https://cafe.naver.com/ca-fe/cafes/22109952/member-level

**Comment by OrigamiDream** [comment]
Fix: 3563e0115fc51b9b39c5052e0bb0cdcaf7d55731
