### ISSUE TITLE
네이버 카페: 안전결제 신청

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#143]
![image](https://user-images.githubusercontent.com/37479424/143733796-d58d5342-8e48-458c-ae2c-68824ef8f317.png)
https://cafe.naver.com/minecraftgame/1838904

**Comment by OrigamiDream** [comment]
Fix: 4d2a88b0d8891d6e3d9efc40a2e9cfe698b82863
