### ISSUE TITLE
네이버 뉴스: 글꼴 조절

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#145]
![image](https://user-images.githubusercontent.com/37479424/144054586-60ae3967-bfde-493c-a4a9-ceff3f449005.png)
https://news.naver.com/main/ranking/read.naver?mode=LSD&mid=shm&sid1=001&oid=015&aid=0004634879&rankingType=RANKING

**Comment by OrigamiDream** [comment]
Fix: c7ac2619f4895098fb3369d1b62e2ca14995ee2b
