### ISSUE TITLE
네이버 검색 : 파주 프로방스

### ISSUE THREAD

**Issue by Radingth** [DarkenPages/Naver-Dark#148]
![image](https://user-images.githubusercontent.com/16663489/145661601-5fc22bc3-7b4a-48fe-ae84-7773fa5f65ca.png)

윈도우 11
크롬
https://search.naver.com/search.naver?where=nexearch&sm=top_hty&fbm=0&ie=utf8&query=%ED%8C%8C%EC%A3%BC+%ED%94%84%EB%A1%9C%EB%B0%A9%EC%8A%A4

**Comment by OrigamiDream** [comment]
Fix: 80b85a917f8d420041d166c8d0126fb74544539c
