### ISSUE TITLE
네이버 검색 : 과자

### ISSUE THREAD

**Issue by Radingth** [DarkenPages/Naver-Dark#150]
![image](https://user-images.githubusercontent.com/16663489/145988124-b325047e-bfc4-4b79-bd04-e23480bb61ee.png)

https://search.naver.com/search.naver?where=nexearch&sm=top_sug.pre&fbm=1&acr=5&acq=%EA%B3%BC%EC%9E%90&qdt=0&ie=utf8&query=%EA%B3%BC%EC%9E%90

크롬
윈도우11

**Comment by OrigamiDream** [comment]
Fix: f5c073bbf20eb1fd42edf8fe564047329029fca2
