### ISSUE TITLE
네이버 공지사항

### ISSUE THREAD

**Issue by Radingth** [DarkenPages/Naver-Dark#151]
![image](https://user-images.githubusercontent.com/16663489/145989019-7485b66d-727b-48e0-9da9-57a848b99623.png)

https://www.naver.com/NOTICE/read/1100001014/10000000000030672420

윈도우11 
크롬

**Comment by OrigamiDream** [comment]
Fix: 6a6810632b7547d372da470e2d5dd2d16c3cfaca
