### ISSUE TITLE
네이버 뉴스: n.news.naver.com

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#152]
https://n.news.naver.com/article/056/0011175478
![image](https://user-images.githubusercontent.com/37479424/145990864-9b917f9b-5b5f-4e9f-b785-58919efce1df.png)

**Comment by OrigamiDream** [comment]
Fix: 82cae36f8eadccd36dcd606ee723842f825ac11a, 37e2090f04073a0b664c0af8ab8e58418fc4e04c, cff1c1366c86c5cda748a1a30616fa3a22d4e2b5
