### ISSUE TITLE
네이버 뉴스 (aka media): *

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#153]
https://media.naver.com/press/052
https://media.naver.com/channel/settings
![image](https://user-images.githubusercontent.com/37479424/145990953-bf3b4660-7bc9-4266-93d8-f3e09e131e65.png)

**Comment by OrigamiDream** [comment]
Fix: 82cae36f8eadccd36dcd606ee723842f825ac11a, 37e2090f04073a0b664c0af8ab8e58418fc4e04c
