### ISSUE TITLE
네이버 검색: 연말정산

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#154]
![image](https://user-images.githubusercontent.com/37479424/145992124-6abaff8f-4360-41c7-acc6-864634156d49.png)
https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=%EC%97%B0%EB%A7%90%EC%A0%95%EC%82%B0&oquery=%EC%97%B0%EB%A7%90&tqi=hkAvgwprvN8ssfQrm9ossssstph-330505

**Comment by OrigamiDream** [comment]
Fix: 7c9847c33764ea88910a653bd6f55eaf29f5e527
