### ISSUE TITLE
네이버 검색: 크리스마스

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#155]
![image](https://user-images.githubusercontent.com/37479424/145992199-ddbde668-0209-4b94-a780-c7f22703181d.png)
https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=%ED%81%AC%EB%A6%AC%EC%8A%A4%EB%A7%88%EC%8A%A4&oquery=%EC%97%B0%EB%A7%90%EC%A0%95%EC%82%B0&tqi=hkAvRwprvmZssg%2FK3ZossssstsG-079462

**Comment by OrigamiDream** [comment]
Fix: 57193d41e6dff0a32bf5db1e2e5513764f8efb2b
