### ISSUE TITLE
네이버 카페 섹션: 검색

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#156]
![image](https://user-images.githubusercontent.com/37479424/145992990-1ae2c7d9-cf02-468a-b242-19f751e9c8fc.png)
![image](https://user-images.githubusercontent.com/37479424/145993044-65ec430f-21b6-4ca2-aa4a-9beb6560dbbd.png)
![image](https://user-images.githubusercontent.com/37479424/145993074-be789545-795a-4446-acaf-d14dcf78021c.png)
https://cafe.naver.com/ca-fe/home/search/articles?q=%EC%A2%86

**Comment by OrigamiDream** [comment]
Fix: 5b913e44200b2799e57bdd1988d39e5dad0211dc
