### ISSUE TITLE
네이버 검색: 붕어빵 만들기

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#161]
거 저어어어어기 오른쪽 하얀색 그라디언트

![image](https://user-images.githubusercontent.com/37479424/147952175-b5d068f8-166d-4f6c-87b8-0aeec9f8961d.png)
https://search.naver.com/search.naver?query=%EB%B6%95%EC%96%B4%EB%B9%B5%EB%A7%8C%EB%93%A4%EA%B8%B0&sm=tab_shk&x_secondlayer=1+50000061+%EC%A3%BC%EB%B0%A9%EC%9A%A9%ED%92%88+false&mra=QkRS^U1BI

**Comment by OrigamiDream** [comment]
Fix: 73615b7e7ab072f7c3ad6facc62cbb8f84ac2e00
