### ISSUE TITLE
네이버 뉴스: 손상된 아이콘들

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#164]
![image](https://user-images.githubusercontent.com/37479424/149650455-2ec3d9af-dd12-4b73-b351-44cc312639ec.png)
https://n.news.naver.com/article/055/0000947001

**Comment by OrigamiDream** [comment]
Fix: de175612c09940f8da624509f67095660643c37b

**Comment by ilsubyeega** [comment]
![image](https://user-images.githubusercontent.com/37479424/150011156-dd136f90-df18-4c42-a467-2c0e8bba6994.png)
![image](https://user-images.githubusercontent.com/37479424/150011176-cf616e68-79dd-49ee-a81e-59c37c1455d6.png)
yee거 아이콘 안바꼈긴 했는데 뭐 /shrug

**Comment by OrigamiDream** [comment]
Fix: 639c8693aaa508d3b3be78863f4a8281446996ef
