### ISSUE TITLE
네이버 뉴스: 디테일

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#165]
![image](https://user-images.githubusercontent.com/37479424/149650537-1bbc6c5d-3de6-452c-bbbb-4b53fbdfc34f.png)
https://news.naver.com/
하얀색 divider랑 아이콘
또한 가능하면 우측 하단 `상단으로 올라가기` 버튼

**Comment by OrigamiDream** [comment]
Fix: 6f09623b16c73c1519a328c43135c287037867ac

우측 하단 버튼은 제외됩니다.
