### ISSUE TITLE
네이버 검색: 거리두기

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#166]
![image](https://user-images.githubusercontent.com/37479424/149668508-8cf22eeb-156d-4dcf-ab10-bbcf7059c78b.png)
![image](https://user-images.githubusercontent.com/37479424/149668517-47807d7d-b2d5-4794-9500-38c393d4c042.png)
https://search.naver.com/search.naver?where=nexearch&sm=top_hty&fbm=0&ie=utf8&query=%EA%B1%B0%EB%A6%AC%EB%91%90%EA%B8%B0

**Comment by OrigamiDream** [comment]
Fix: 2262e6d2f92d29e0fc524108eb7266226ba139e0
