### ISSUE TITLE
네이버 카페 회원 정보 확인

### ISSUE THREAD

**Issue by PeraSite** [DarkenPages/Naver-Dark#167]
![image](https://user-images.githubusercontent.com/19837403/154079018-0f7daeb4-97fb-424b-add8-a0d5c47531c0.png)

**Comment by OrigamiDream** [comment]
문제가 확인되지 않습니다.
최신 버전으로 업데이트하셨나요?

**Comment by OrigamiDream** [comment]
최신 버전에서 문제 수정됨을 확인
