### ISSUE TITLE
네이버 검색: 베이징 동계올림픽 폐막

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#169]
![image](https://user-images.githubusercontent.com/37479424/154813108-f4421e06-a34c-4875-ba98-48c8a077d89d.png)
https://search.naver.com/search.naver?where=nexearch&sm=top_brd&fbm=1&ie=utf8&query=%EB%B2%A0%EC%9D%B4%EC%A7%95+%EB%8F%99%EA%B3%84%EC%98%AC%EB%A6%BC%ED%94%BD+%ED%8F%90%EB%A7%89

**Comment by OrigamiDream** [comment]
Fix: 4d97ddb5efab1259b8a51a40fff2d4b76e9f8ea5
