### ISSUE TITLE
네이버 검색 : 코로나19 병상 가동률 

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#171]
![image](https://user-images.githubusercontent.com/42881884/157367421-3e89e6ff-2dc7-4b98-afd6-44be02c5c3f9.png)

Link: https://search.naver.com/search.naver?where=nexearch&query=%EC%BD%94%EB%A1%9C%EB%82%9819+%EB%B3%91%EC%83%81%EA%B0%80%EB%8F%99%EB%A5%A0

**Comment by OrigamiDream** [comment]
Fix: f701c4a0e289ec275ac1966016038bbc05228efa
