### ISSUE TITLE
시청률 / 라디오 주파수

### ISSUE THREAD

**Issue by aroxu** [DarkenPages/Naver-Dark#172]
시청률
![image](https://user-images.githubusercontent.com/30624945/159160719-224fd958-be0e-4825-a6da-098179d6450e.png)
라디오 주파수
![image](https://user-images.githubusercontent.com/30624945/159160733-f00a5a20-433b-4fd8-859a-240d9072d5e6.png)

**Comment by OrigamiDream** [comment]
Fix: 4b3355f135f5357d68ce24ea18cf16fbdb474587, ef268597db9c16530ace17f24765be2e66832966
