### ISSUE TITLE
네이버 검색 / 한자

### ISSUE THREAD

**Issue by aroxu** [DarkenPages/Naver-Dark#175]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/30624945/162664742-2d8a43a4-1003-41b2-ab67-07e1cbf5f958.png">

**Comment by aroxu** [comment]
<img width="499" alt="image" src="https://user-images.githubusercontent.com/30624945/162665034-2266d299-22d3-4e28-bbc8-47bd9276b578.png">

**Comment by OrigamiDream** [comment]
Fix: cc736a480ada18414de06e5ee6687aba101491f2
