### ISSUE TITLE
네이버 검색 동영상 

### ISSUE THREAD

**Issue by Radingth** [DarkenPages/Naver-Dark#181]
![image](https://user-images.githubusercontent.com/16663489/169052315-3847bd69-e59a-4994-a4ce-252a59126f83.png)

https://search.naver.com/search.naver?sm=tab_hty.top&where=video&query=%EC%9E%89%3F&oquery=%ED%8C%8C%ED%8C%9014&tqi=hog2Fdp0Jy0ssDh70ZCssssssiV-290261

크롬 
윈도우 11

**Comment by OrigamiDream** [comment]
Fix 3fb7e9e262e589c2708a9aa36a25f796b8c2c835
