### ISSUE TITLE
네이버 뉴스쪽 다크모드 오류

### ISSUE THREAD

**Issue by z3nguy** [DarkenPages/Naver-Dark#200]
https://media.naver.com/press/011?sid=100

이미지 첨부는 되질 않나 보군요. 네이버 뉴스 각 언론사 페이지에 들어갔을 시.. 다크 모드가 제대로 적용되지 않아 기사 제목을 원활히 확인 하기가 어렵네요.

확인하여 주시면 감사하겠습니다.

항상. 감사히 잘 쓰고 있습니다.

**Comment by OrigamiDream** [comment]
사용하시는 브라우저를 알 수 있을까요?
Safari 16.0 기준 기사 제목이 정상적으로 표시됩니다.

**Comment by z3nguy** [comment]
윈도우11 에서 크롬 사용 중입니다.

**Comment by OrigamiDream** [comment]
Resolved in 4d59dd1
