### ISSUE TITLE
네이버 뉴스 리스트 화면과 기사 본문 화면이 다릅니다.

### ISSUE THREAD

**Issue by z3nguy** [DarkenPages/Naver-Dark#201]
https://news.naver.com/main/main.naver?mode=LSD&mid=shm&sid1=100
![image](https://user-images.githubusercontent.com/114352280/192153129-02ed3fb0-531e-41e1-b227-9ea32c64dc19.png)

https://n.news.naver.com/mnews/article/277/0005152170?sid=101
![image](https://user-images.githubusercontent.com/114352280/192153142-6d12920d-17ae-4acf-9695-ee97347e5a20.png)

위와 같이  뉴스 제목만 있는 화면과 본문 화면과 상단부 메뉴 백그라운드 다크 모드가 상이하게 표시 되네요.

확인 부탁 드립니다.

감사합니다.

**Comment by OrigamiDream** [comment]
news.naver.com와 n.news.naver.com는 네이버 자체에서 서로 다르게 관리되는 별개의 페이지입니다.
따라서 페이지 전체적으로 일부 폰트 및 디자인이 상이할 수 있습니다.

다만 사용자 경험에서의 일관성은 필요하므로, 해당 사항 수정토록 하겠습니다.

**Comment by OrigamiDream** [comment]
Resolved in efaf1ed
