### ISSUE TITLE
upm.search.naver.com

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#210]
![image](https://user-images.githubusercontent.com/37479424/204132634-a71ead7b-0e53-466f-a7c8-269cac3aad67.png)
https://upm.search.naver.com/upm/p?nxCode=xea&subject=%EC%B6%95%EA%B5%AC%EC%9D%B4%EB%B2%A4%ED%8A%B8%EB%8C%80%ED%9A%8C&objectTitle=2022%20%EC%B9%B4%ED%83%80%EB%A5%B4%20%EC%9B%94%EB%93%9C%EC%BB%B5&objectId=29008840&keyword=%EC%B9%B4%ED%83%80%EB%A5%B4%EC%9B%94%EB%93%9C%EC%BB%B5

**Comment by OrigamiDream** [comment]
Resolved: 9bd97bc68e4811f84d33b6bad2fc4fd880a4602c
