### ISSUE TITLE
네이버ID

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#220]
![image](https://user-images.githubusercontent.com/37479424/210226545-b67271e7-7de9-402e-8771-5da6bcc9a245.png)
https://nid.naver.com/user2/help/myInfoV2?m=viewSecurity&lang=ko_KR

**Comment by ilsubyeega** [comment]
![image](https://user-images.githubusercontent.com/37479424/210226600-d2b5971a-e0d3-4017-8777-e5c58a988a0b.png)

**Comment by OrigamiDream** [comment]
Resolved from d98608c6f1cc0964df8c84d0f96ae3d0680ad1b3
