### ISSUE TITLE
메일 읽을 때 배경, 네이버 쇼핑 쪽...

### ISSUE THREAD

**Issue by GOONSPEOPLE** [DarkenPages/Naver-Dark#40]
허옇게 나오네용 ㅠ
![1](https://user-images.githubusercontent.com/39190567/80505094-d9d2b100-89ae-11ea-957a-7f4e60f91acf.png)
![2](https://user-images.githubusercontent.com/39190567/80505185-f66ee900-89ae-11ea-9444-429036d7397c.png)

**Comment by OrigamiDream** [comment]
쇼핑은 추후 작업 예정에 있습니다.

메일 콘텐츠 부분의 경우 보내는 쪽에서 레이아웃을 굉장히 다양하게 보낼 수 있기 때문에 CSS 상에서 모든 레이아웃에 대한 처리가 불가능하며, 이는 다크 테마를 지원하는 Gmail 의 사례에서도 동일합니다.

보내주신 메일 파트는 흰색 배경으로 교체됩니다.
