### ISSUE TITLE
메인에서 버튼 하양이 문제

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#41]
![image](https://user-images.githubusercontent.com/37479424/83160409-20e4cb00-a142-11ea-8c88-7838d9e78ae4.png)

[이 이미지](https://s.pstatic.net/static/www/img/uit/2020/sp_main.d9a208.png)를 수정해야 할듯요

**Comment by OrigamiDream** [comment]
해당 버튼들은 콘텐츠 및 액션 강조를 위해 의도적으로 희게 둔 버튼들입니다.
