### ISSUE TITLE
유지보수 이루어지나요?

### ISSUE THREAD

**Issue by cykablyat0001a** [DarkenPages/Naver-Dark#43]
네이버 다크모드는 별로 다크모드 같지도 않고, 진짜 다크모드도 아닙니다. 메인 화면만 어둡게 바꿔놓고 다른 서비스들은 싹다 멀쩡한데 이게 진짜 다크모드라고 볼 수 없죠... 웨일 쓰게 만드려는 그런거 같은데...

혹시 유지보수 안해주시나요?? 이 다크모드 정말 잘 사용하고 있었는데 참고 쓰고 있다가 글 남겨봅니다.

**Comment by OrigamiDream** [comment]
저번에 네이버에서 검색 페이지, 카페 페이지, TALK 페이지 등등 상당히 많은 부분이 바뀌게 되어 제 작업속도가 따라가지 못하고 있습니다.
제 로컬 컴퓨터에서는 개선이 계속 이루어 지고 있으나, 이 개선된 사항들이 업로드 되지 않은 상황입니다.

빠른 시일 내에 새로운 업데이트를 게시할 예정이기 때문에, 현 GitHub 페이지 우측 상단 Watch 버튼을 눌러서 알람을 받으시면 업데이트 게시 시 GitHub 에서 사용하시는 이메일로 업데이트 내역을 받으실 수 있겠습니다.
