### ISSUE TITLE
네이버 검색 학교 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#64]
플랫폼: windows
해상도: FHD
브라우저: Firefox

링크: https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=유치원

링크: https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=초등학교

링크: https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=중학교

링크: https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=고등학교

링크: https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=대학교

**Comment by OrigamiDream** [comment]
Fix: e1505cfb3217906a29f1af36bbe95999a0340ca0
