### ISSUE TITLE
네이버 검색: 플레이스

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#66]
https://search.naver.com/search.naver?query=%EC%A0%84%EB%9D%BC%EB%B6%81%EB%8F%84+%EA%B5%B0%EC%82%B0%EC%8B%9C+%ED%95%98%EB%82%98%EC%9A%B4%EB%A1%9C+20
![image](https://user-images.githubusercontent.com/37479424/131188535-2394e5ee-fb16-4e5c-852e-b556df8271e2.png)

**Comment by OrigamiDream** [comment]
Fix: e1505cfb3217906a29f1af36bbe95999a0340ca0
