### ISSUE TITLE
네이버 검색: 인천공항 운항정보

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#67]
https://search.naver.com/search.naver?query=%EC%9D%B8%EC%B2%9C%EA%B3%B5%ED%95%AD
![image](https://user-images.githubusercontent.com/37479424/131188784-27779141-e4cb-41e4-a26c-721ef004886b.png)

**Comment by OrigamiDream** [comment]
Fix: e1505cfb3217906a29f1af36bbe95999a0340ca0
