### ISSUE TITLE
네이버 검색: 도서

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#68]
https://search.naver.com/search.naver?query=%EC%9A%B0%EB%A6%AC%EA%B0%80+%EB%B9%9B%EC%9D%98+%EC%86%8D%EB%8F%84%EB%A1%9C+%EA%B0%88+%EC%88%98+%EC%97%86%EB%8B%A4%EB%A9%B4
![image](https://user-images.githubusercontent.com/37479424/131189108-a7142416-3d33-4f02-ba82-f3c681099a37.png)

**Comment by OrigamiDream** [comment]
Fix: e1505cfb3217906a29f1af36bbe95999a0340ca0
