### ISSUE TITLE
네이버 검색: 연극정보

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#69]
지도 아이콘 하양이
https://search.naver.com/search.naver?where=nexearch&sm=tab_etc&mra=bkkw&pkid=269&os=9885137&qvt=0&query=%EA%B9%80%EC%B9%98
![image](https://user-images.githubusercontent.com/37479424/131189258-2e3ab065-440c-43dc-9aa7-2b929aafd877.png)

**Comment by OrigamiDream** [comment]
Fix: e1505cfb3217906a29f1af36bbe95999a0340ca0
