### ISSUE TITLE
네이버 검색: 영화예매사이트

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#70]
![image](https://user-images.githubusercontent.com/37479424/131189379-d2131add-ea03-4d52-a10e-127d116a67de.png)
https://search.naver.com/search.naver?where=nexearch&sm=tab_etc&qvt=0&query=%EC%98%81%ED%99%94%EC%98%88%EB%A7%A4%EC%82%AC%EC%9D%B4%ED%8A%B8

arrow button 배경처리 안됨

**Comment by OrigamiDream** [comment]
Fix: e1505cfb3217906a29f1af36bbe95999a0340ca0
