### ISSUE TITLE
네이버 검색: 온라인 공개 강좌

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#71]
https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=github&oquery=%EC%82%AC%EC%A7%84%EC%B2%A9&tqi=hfDT6dp0J1ssslsU650ssssstZR-280655
![image](https://user-images.githubusercontent.com/37479424/131189529-a22f132f-79c3-4174-8823-0c386dd901b6.png)
내부 하얀색

**Comment by OrigamiDream** [comment]
Fix: e1505cfb3217906a29f1af36bbe95999a0340ca0
