### ISSUE TITLE
네이버 검색 게임 경기일정 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#73]
플랫폼: windows
해상도: FHD
브라우저: Firefox

예시링크 : https://search.naver.com/search.naver?where=nexearch&sm=top_hty&fbm=1&ie=utf8&query=t1

예시링크 : https://search.naver.com/search.naver?where=nexearch&sm=top_hty&fbm=1&ie=utf8&query=lck

예시링크 : https://search.naver.com/search.naver?where=nexearch&query=lpl&ie=utf8&sm=tab_she&qdt=0

![image](https://user-images.githubusercontent.com/42881884/131215316-2c0b7a5f-781a-438c-97db-bb658db19845.png)

**Comment by OrigamiDream** [comment]
Fix: 943e475d28ce67eb4e009a31e61f1aaa6b320a0f
