### ISSUE TITLE
네이버 검색 채용정보 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#74]
플랫폼: windows
해상도: FHD
브라우저: Firefox

예시링크 : https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=삼성+채용정보

![image](https://user-images.githubusercontent.com/42881884/131215381-115f634d-9dba-4b7a-87f5-829f76e939ae.png)

**Comment by OrigamiDream** [comment]
Fix: 943e475d28ce67eb4e009a31e61f1aaa6b320a0f
