### ISSUE TITLE
네이버 검색 마약류 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#75]
플랫폼: windows
해상도: FHD
브라우저: Firefox

https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=메스암페타민

![image](https://user-images.githubusercontent.com/42881884/131215487-30b92426-0672-4aea-870a-4f4fdd80e5ea.png)

**Comment by OrigamiDream** [comment]
Fix: 943e475d28ce67eb4e009a31e61f1aaa6b320a0f
