### ISSUE TITLE
네이버 검색 오디오클립 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#76]
플랫폼: windows
해상도: FHD
브라우저: Firefox

https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=BBC

![image](https://user-images.githubusercontent.com/42881884/131215511-77d306a7-7819-4239-8bcc-9e3269c92a99.png)

**Comment by OrigamiDream** [comment]
Fix: 943e475d28ce67eb4e009a31e61f1aaa6b320a0f
