### ISSUE TITLE
네이버 검색 대학교 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#77]
플랫폼: windows
해상도: FHD
브라우저: Firefox

https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=서울사이버대학교

![image](https://user-images.githubusercontent.com/42881884/131215618-141d0131-aca7-4727-9f3d-0496bfec9110.png)

**Comment by winter0729** [comment]
학사통계 | 경쟁률  부분 수정필요.

**Comment by OrigamiDream** [comment]
Fix: 943e475d28ce67eb4e009a31e61f1aaa6b320a0f
