### ISSUE TITLE
네이버 검색 번역보기 버튼 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#78]
플랫폼: windows
해상도: FHD
브라우저: Firefox

https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=나스닥

![image](https://user-images.githubusercontent.com/42881884/131215749-fe61137f-aea9-4bb6-ba96-ed46dba7f398.png)

**Comment by OrigamiDream** [comment]
Fix: 943e475d28ce67eb4e009a31e61f1aaa6b320a0f
