### ISSUE TITLE
네이버 검색 시간 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#79]
플랫폼: windows
해상도: FHD
브라우저: Firefox
https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=시간

![image](https://user-images.githubusercontent.com/42881884/131215847-71fe31a9-e7b3-4fe9-b6ba-1b97a02eb349.png)

**Comment by winter0729** [comment]
네이버 시계
세계시간 > 주요도시 | 도시선택 버튼
국가번호 > 지역선택 | 직접입력 버튼

수정필요

**Comment by OrigamiDream** [comment]
각 버튼은 의도된 것임

Fix: 5cde4bd97b5f6cbff3b3e2ab6947c8156ae941bc
