### ISSUE TITLE
네이버 검색 법률 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#80]
플랫폼: windows
해상도: FHD
브라우저: Firefox

https://search.naver.com/search.naver?where=nexearch&sm=top_hty&fbm=1&ie=utf8&query=법률

![image](https://user-images.githubusercontent.com/42881884/131216040-55b191c4-66e4-44ef-9920-34e3df866eb0.png)

**Comment by OrigamiDream** [comment]
Fix: 385782e500f312a574e803c6822916d14bc6f9db
