### ISSUE TITLE
네이버 검색 노래 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#81]
플랫폼: windows
해상도: FHD
브라우저: Firefox

https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=노래

![image](https://user-images.githubusercontent.com/42881884/131216107-03f5d973-c23a-47e5-be82-da4cfe7417ff.png)

**Comment by OrigamiDream** [comment]
Fix: 385782e500f312a574e803c6822916d14bc6f9db
