### ISSUE TITLE
네이버 메일 스팸메일함 비우기 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#82]
플랫폼: windows
해상도: FHD
브라우저: Firefox

링크 : https://mail.naver.com/

좌측 메뉴에서 아랫부분 메일 스팸함부분 쓰래기통 버튼을 누를시 나옴.

![image](https://user-images.githubusercontent.com/42881884/131216607-0412723a-688e-40d7-9351-a30489d9fe58.png)

![image](https://user-images.githubusercontent.com/42881884/131216602-07bf4a6d-cb2a-4f5c-b077-994ea882058c.png)

**Comment by OrigamiDream** [comment]
Fix: 9e1f71432926d7889bbfe222a7fd911bd01f54bb
