### ISSUE TITLE
네이버 쪽지: 목록

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#83]
![image](https://user-images.githubusercontent.com/37479424/131216696-b4d1c93c-dfb3-4618-af5c-4cfad6b0b26f.png)
https://note.naver.com/
링크 색상이 메일보다 더 탁함

**Comment by OrigamiDream** [comment]
Fix: 15788b394acd98ab9f43f00230decdb36805486d
