### ISSUE TITLE
네이버 검색 타임라인 바 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#84]
플랫폼: windows
해상도: FHD
브라우저: Firefox

https://search.naver.com/search.naver?query=%EC%95%BC%EC%98%B9&nso=&where=view&sm=tab_viw.all&mode=timeline

![image](https://user-images.githubusercontent.com/42881884/131216751-dd621e35-0a4f-4e39-b9dc-93e749ae5c42.png)

**Comment by OrigamiDream** [comment]
Fix: 385782e500f312a574e803c6822916d14bc6f9db
