### ISSUE TITLE
네이버 검색 미술정보 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#86]
플랫폼: windows
해상도: FHD
브라우저: Firefox

https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=#고양이

![image](https://user-images.githubusercontent.com/42881884/131216837-14a43794-421f-4d20-b6c0-d515827bc32f.png)

**Comment by winter0729** [comment]
작품감상하기 버튼에 마우스 올리면뜨는 레이아웃.

![image](https://user-images.githubusercontent.com/42881884/131216893-8b4360d0-95fe-4a90-ba17-0bd3887500c5.png)

**Comment by OrigamiDream** [comment]
Fix: 385782e500f312a574e803c6822916d14bc6f9db
