### ISSUE TITLE
네이버 검색 동영상 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#87]
플랫폼: windows
해상도: FHD
브라우저: Firefox

https://search.naver.com/search.naver?sm=tab_hty.top&where=video&query=고양이

![image](https://user-images.githubusercontent.com/42881884/131216957-6d2624c2-2b4a-410d-9de1-fb719bb6ed99.png)

**Comment by winter0729** [comment]
추천 채널 글씨가 보이지않음.

![image](https://user-images.githubusercontent.com/42881884/131216962-331c563b-40fa-40f1-abd8-2c4de591fd16.png)

**Comment by winter0729** [comment]
동영상 클릭시 하얀바가 생김. 

![image](https://user-images.githubusercontent.com/42881884/131217029-3abda91d-f4c6-4e6b-aff8-3123c9f0aa97.png)

**Comment by OrigamiDream** [comment]
Fix: 385782e500f312a574e803c6822916d14bc6f9db, cd2a51653bad384831485ca066cd879a5e0da169
