### ISSUE TITLE
네이버 검색 글자수세기 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#89]
플랫폼: windows
해상도: FHD
브라우저: Firefox

링크: https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=글자수세기

![image](https://user-images.githubusercontent.com/42881884/131227058-faaec241-8a60-47b8-b89b-5987ee9fc160.png)

**Comment by OrigamiDream** [comment]
Fix: 385782e500f312a574e803c6822916d14bc6f9db
