### ISSUE TITLE
네이버 검색 병원 플레이스 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#90]
플랫폼: windows
해상도: FHD
브라우저: Firefox

예시 링크: https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=피부과

![image](https://user-images.githubusercontent.com/42881884/131227203-70410879-d3e8-45bb-9fa4-6bda0aebef5a.png)

**Comment by winter0729** [comment]
이전 / 다음 글씨가 보이지않음.

![image](https://user-images.githubusercontent.com/42881884/131227214-20c25e6a-8c68-4a02-ad42-f4a6f6cbdc89.png)

**Comment by OrigamiDream** [comment]
이전 / 다음 글씨는 네이버가 장애인 접근성 지원 차원으로 추가한 문구로 색상이 없는 글씨입니다.
Fix: 385782e500f312a574e803c6822916d14bc6f9db
