### ISSUE TITLE
네이버 검색 파워링크 위치 미리보기 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#91]
플랫폼: windows
해상도: FHD
브라우저: Firefox

예시링크: https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=음식점

![image](https://user-images.githubusercontent.com/42881884/131227270-5b9233db-8d6d-473b-bd38-07c216500855.png)

**Comment by OrigamiDream** [comment]
Fix: 385782e500f312a574e803c6822916d14bc6f9db
