### ISSUE TITLE
네이버 검색 이미지신고 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#92]
플랫폼: windows
해상도: FHD
브라우저: Firefox

예시링크 : https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=고양이

![image](https://user-images.githubusercontent.com/42881884/131227326-086a8e96-b835-4557-960b-ca4fa63b1390.png)

**Comment by OrigamiDream** [comment]
Fix: 385782e500f312a574e803c6822916d14bc6f9db
