### ISSUE TITLE
네이버 카페: 탈퇴 완료

### ISSUE THREAD

**Issue by ilsubyeega** [DarkenPages/Naver-Dark#93]
![image](https://user-images.githubusercontent.com/37479424/131246074-ea0e033c-a06d-4fc6-804b-ae80fb1ef149.png)
url 자체는 https://cafe.naver.com/CafeSecede.nhn, 카페 탈퇴 요청이 필요함

**Comment by OrigamiDream** [comment]
Fix: 410c583f663e17abee5e8b756b99e4ddae722d0e
