### ISSUE TITLE
네이버 전화번호 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#94]
플랫폼: windows
해상도: FHD
브라우저: Firefox

링크: https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=1339

![image](https://user-images.githubusercontent.com/42881884/131475285-b8a1bb52-0223-4030-b2c7-776b0ddc76c8.png)

**Comment by OrigamiDream** [comment]
Fix: 74797be4c81b7da35bccead1066f81e34eb26662
