### ISSUE TITLE
네이버 도박중독 예방 캠페인 레이아웃 

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#95]
플랫폼: windows
해상도: FHD
브라우저: Firefox

링크: https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=도박

![image](https://user-images.githubusercontent.com/42881884/131475525-01b27c60-3f4e-4939-94b7-b36baf4fc0d3.png)

**Comment by OrigamiDream** [comment]
Fix: 2bcfc826f7a0367e8c07bf763e4351511d1e9dd0
