### ISSUE TITLE
네이버 검색 공유 > Keep 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#96]
플랫폼: windows
해상도: FHD
브라우저: Firefox

https://search.naver.com/search.naver?sm=top_hty&fbm=0&ie=utf8&query=코로나19

![image](https://user-images.githubusercontent.com/42881884/131476606-257660cd-d347-4d4e-964d-6fb59462dfd9.png)

**Comment by OrigamiDream** [comment]
Fix: 4c7e4da414cc528d0bccf77ffc9f4d79da5be868
