### ISSUE TITLE
네이버 검색 제철음식 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#97]
플랫폼: windows
해상도: FHD
브라우저: Firefox

예시링크 : https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=복숭아

![image](https://user-images.githubusercontent.com/42881884/131780036-c108a6b0-d712-4d42-8f60-addc70e18adb.png)

**Comment by OrigamiDream** [comment]
Fix: dffd0c9477fa582f5288f94629c63b5368368351
