### ISSUE TITLE
네이버 검색 Keep 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#98]
플랫폼: windows
해상도: FHD
브라우저: Firefox

예시링크 : https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=코로나

![image](https://user-images.githubusercontent.com/42881884/131780188-336bc586-c627-4a6d-8319-3c1fde95929f.png)

**Comment by winter0729** [comment]
코로나 관련 글 Keep 저장 필요

![image](https://user-images.githubusercontent.com/42881884/131780221-a0ccdcd7-9601-43f5-89a8-f18b17132e90.png)

**Comment by OrigamiDream** [comment]
Fix: 5788b757df0c17453a94087afa451b135445a3a2
