### ISSUE TITLE
네이버 검색 드라마 레이아웃

### ISSUE THREAD

**Issue by winter0729** [DarkenPages/Naver-Dark#99]
플랫폼: windows
해상도: FHD
브라우저: Firefox

예시링크 : https://search.naver.com/search.naver?sm=tab_hty.top&where=nexearch&query=드라마

![image](https://user-images.githubusercontent.com/42881884/131780512-297bfd26-e3c8-4719-8d39-c0dfa5cf4dca.png)

**Comment by OrigamiDream** [comment]
Fix: 35b6853c2cfdce0d258b5ac288ad4361e5bab7d3
